[package]
name = "baseball-streams"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
reqwest = "0.12.22"
serde_json = "1.0.140"
tokio = { version = "1.46.1", features = ["full"] }
